"""Mirror of crates/shared/src/constants.rs — all game constants for GPU sim."""

import math

# Tick rate
TICK_RATE = 120
DT = 1.0 / TICK_RATE  # 0.00833...

# Match
MATCH_DURATION_SECS = 90
MAX_TICKS = TICK_RATE * MATCH_DURATION_SECS  # 10800

# Arena (side-view: X=horizontal, Y=altitude)
ARENA_RADIUS = 500.0
ARENA_DIAMETER = ARENA_RADIUS * 2.0  # 1000.0
BOUNDARY_START_HORIZ = 450.0
BOUNDARY_FORCE = 300.0
GRAVITY = 130.0
MAX_ALTITUDE = 600.0
ALT_BOUNDARY_LOW = 50.0
ALT_BOUNDARY_HIGH = 550.0

# Fighter
FIGHTER_RADIUS = 8.0
MAX_SPEED = 250.0
MIN_SPEED = 20.0
MAX_THRUST = 180.0
DRAG_COEFF = 0.9
MAX_TURN_RATE = 4.0
MIN_TURN_RATE = 0.8
TURN_BLEED_COEFF = 0.25
MAX_HP = 5

# Stall
STALL_SPEED = 30.0
STALL_RECOVERY_TICKS = 36  # ~0.3s at 120Hz
STALL_NOSE_DOWN_RATE = 2.5  # rad/s

# Damage degradation
DAMAGE_SPEED_PENALTY = 0.03
DAMAGE_TURN_PENALTY = 0.02

# Bullets
BULLET_SPEED = 400.0
BULLET_LIFETIME_TICKS = 60  # 0.5s at 120Hz
BULLET_RADIUS = 3.0
GUN_COOLDOWN_TICKS = 90  # 0.75s at 120Hz

# Rear-aspect armor
REAR_ASPECT_CONE = 0.785  # PI/4 ≈ 45-deg half-angle (matches Rust literal)

# Observation
SINGLE_FRAME_OBS_SIZE = 56
FRAME_STACK_SIZE = 4
OBS_SIZE = SINGLE_FRAME_OBS_SIZE * FRAME_STACK_SIZE  # 224
ACTION_SIZE = 3
MAX_BULLET_SLOTS = 8

# Control
CONTROL_PERIOD = 10  # 12Hz decisions at 120Hz physics

# Energy normalization
MAX_ENERGY = MAX_SPEED * MAX_SPEED + 2.0 * GRAVITY * MAX_ALTITUDE

# Config observation (legacy)
CONFIG_OBS_SIZE = 13

# Fixed normalization denominators for config observation
CONFIG_NORM_GRAVITY = 200.0
CONFIG_NORM_DRAG_COEFF = 2.0
CONFIG_NORM_TURN_BLEED_COEFF = 1.0
CONFIG_NORM_MAX_SPEED = 500.0
CONFIG_NORM_MIN_SPEED = 100.0
CONFIG_NORM_MAX_THRUST = 400.0
CONFIG_NORM_BULLET_SPEED = 800.0
CONFIG_NORM_GUN_COOLDOWN_TICKS = 240.0
CONFIG_NORM_BULLET_LIFETIME_TICKS = 180.0
CONFIG_NORM_MAX_HP = 10.0
CONFIG_NORM_MAX_TURN_RATE = 8.0
CONFIG_NORM_MIN_TURN_RATE = 4.0
CONFIG_NORM_REAR_ASPECT_CONE = math.pi

# Bullets per env (fixed pool size)
BULLETS_PER_ENV = 24

# Opponent type IDs
OPP_DO_NOTHING = 0
OPP_CHASER = 1
OPP_DOGFIGHTER = 2
OPP_ACE = 3
OPP_BRAWLER = 4

# Dogfighter modes
MODE_ATTACK = 0
MODE_DEFEND = 1
MODE_ENERGY = 2
MODE_DISENGAGE = 3

# Brawler phases
PHASE_CLOSE = 0
PHASE_BRAWL = 1
PHASE_OVERSHOOT_BAIT = 2
PHASE_OVERSHOOT_PUNISH = 3
PHASE_RETREAT = 4

# Default reward weights
DEFAULT_W_DAMAGE_DEALT = 3.0
DEFAULT_W_DAMAGE_TAKEN = -1.0
DEFAULT_W_WIN = 5.0
DEFAULT_W_LOSE = -5.0
DEFAULT_W_APPROACH = 0.0001
DEFAULT_W_ALIVE = 0.0
DEFAULT_W_PROXIMITY = 0.001
DEFAULT_W_FACING = 0.0005
